fast_lap = race_data.laps.pick_fastest()

print(f"Fastest Lap Driver: {fast_lap['Driver']}")
print(f"Fastest Driver Team: {fast_lap['Team']}")
print(f"Fastest Driver Position: {fast_lap['Position']}")
print(f"Fastest LapTime: {fast_lap['LapTime']}")
print(f"Fastest LapNumber: {fast_lap['LapNumber']}")
print(f"\t Fastest Sector 1: {fast_lap['Sector1Time']}")
print(f"\t Fastest Sector 2: {fast_lap['Sector2Time']}")
print(f"\t Fastest Sector 3: {fast_lap['Sector3Time']}")
